queue_rules:
  - name: commit
    queue_conditions:
      - or:
          - author = writer
      - review-requested = codingrabbitai
      - review-requested = bearycool11
      - and:
          - check-success = continuous-integration/travis-ci
    merge_conditions:
      - merged
      - and:
          - check-success = continuous-integration/travis-ci
